Repository gridcoin-community/Gridcoin-Site, pull requests merged in 2019-06, with the labels that each got.

#200 add font-display: swap;
  assets/css/now-ui-kit.css
Labels: question

#175 Issue#79 - Dynamic version number
  _includes/_wallet_install.htm
  _layouts/layout.htm
  assets/js/fetch-release.js
  index.htm
  source/assets/js/fetch-release.js
Labels: enhancement

#204 Fix issues highlighted by name831
  _data/blog.yml
  _includes/_solo_boinc_intro.htm
  _includes/_wallet_install.htm
Labels: bug

#176 Update bootstrap from V4-Alpha6 to V4.3.1
  Guides/terminology.htm
  Guides/whitelist.htm
  _includes/_head.htm
  _layouts/layout.htm
  assets/css/bootstrap.min.css
  assets/css/bootstrap.min.css.map
  assets/css/gridcoin.css
  assets/js/core/bootstrap.bundle.min.js
  assets/js/core/bootstrap.bundle.min.js.map
  assets/js/core/jquery-3.4.1.min.js
  index.htm
Labels: enhancement

#208 Rewrite Navbar and remove now-ui.
  Dev/rpc-reference.htm
  Guides/acquire-grc.htm
  Guides/boinc-install.htm
  Guides/earn-grc.htm
  Guides/gridcoin-install.htm
  Guides/investor-acquire-grc.htm
  Guides/investor-earn-grc.htm
  Guides/investor-gridcoin-setup.htm
  Guides/misc.htm
  Guides/pool-gridcoin-install.htm
  Guides/pool.htm
  Guides/security.htm
  Guides/terminology.htm
  Guides/whitelist.htm
  _includes/_acquire.htm
  _includes/_acquire_details.htm
  _includes/_boinc_1A.htm
  _includes/_boinc_1B.htm
  _includes/_boinc_1C.htm
  _includes/_footer.htm
  _includes/_head.htm
  _includes/_header.htm
  _includes/_solo_boinc_intro.htm
  _includes/_wallet_install.htm
  _layouts/layout.htm
  assets/css/easyTable.css
  assets/css/gridcoin.css
  assets/css/now-ui-kit.css
  assets/css/open-iconic-bootstrap.css
  assets/css/table.css
  assets/fonts/open-iconic.woff
  assets/js/core/tether.min.js
  assets/js/easyTable.js
  assets/js/fetch-release.js
  assets/js/now-ui-kit.js
  assets/js/plugins/bootstrap-datepicker.js
  assets/js/plugins/bootstrap-switch.js
  assets/js/plugins/moment.min.js
  assets/js/plugins/nouislider.min.js
  blog.htm
  contact.htm
  exchange.htm
  index.htm
Labels: enhancement
