Repository gridcoin-community/Gridcoin-Site, pull requests merged in 2021-04, with the labels that each got.

#295 Update ci.yaml
  .github/workflows/ci.yaml
Labels: enhancement

#292 jQuery Upgrade
  _layouts/layout.htm
  _layouts/wiki-de.html
  _layouts/wiki-sv.html
  _layouts/wiki.html
  assets/js/core/jquery-3.5.1.min.js
  assets/js/core/jquery-3.6.0.min.js
Labels: enhancement

#291 Removal of Blog resource
  README.md
  _data/blog.yml
  _data/readme.md
  _includes/_footer.htm
  _includes/_header.htm
  assets/css/gridcoin.css
  blog.htm
Labels: cleanup

#293 Formatting fixes from jslint
  assets/js/fetch-release.js
Labels: cleanup

#298 Update to bootstrap 4.6.0
  _includes/_head.htm
  _layouts/layout.htm
  _layouts/wiki-de.html
  _layouts/wiki-sv.html
  _layouts/wiki.html
  assets/css/bootstrap-4.3.1.min.css
  assets/css/bootstrap-4.3.1.min.css.map
  assets/css/bootstrap-4.6.0.min.css
  assets/css/bootstrap-4.6.0.min.css.map
  assets/js/core/bootstrap-4.3.1.bundle.min.js
  assets/js/core/bootstrap-4.3.1.bundle.min.js.map
  assets/js/core/bootstrap-4.6.0.bundle.min.js
  assets/js/core/bootstrap-4.6.0.bundle.min.js.map
Labels: Dependencies
