Repository gridcoin-community/Gridcoin-Site, pull requests merged in 2023-04, with the labels that each got.

#372 Clarify language around rpc command rpcallowip
  wiki/cmd-options.md
  wiki/config-file.md
  wiki/rpc.md
Labels: bug, Priority

#371 Various edits to improve accessibility of user guides
  _data/whitelist.yml
  _includes/_acquire_details.htm
  _includes/_boinc_1B.htm
  _includes/_boinc_1C.htm
  _includes/_solo_boinc_intro.htm
  guides/earn-grc.htm
  guides/foldingathome.htm
  guides/noncruncher-gridcoin-setup.htm
  guides/optimization.htm
  guides/pool.htm
  index.htm
Labels: enhancement, cleanup

#373 Whitelist improvements + Fix for Linux BOINC installers
  _data/whitelist.yml
  _includes/_solo_boinc_intro.htm
  assets/img/amd_badge.png
  assets/img/nvidia_badge.png
  guides/whitelist.htm
Labels: enhancement

#374 Various edits to site to update documentation
  _includes/_acquire.htm
  _includes/_boinc_1B.htm
  _includes/_header.htm
  _includes/_solo_boinc_intro.htm
  _includes/_wallet_install.htm
  contact.htm
  guides/earn-grc.htm
  guides/gridcoin-install.htm
  guides/whitelist.htm
  index.htm
  wiki/advantages-and-features.md
  wiki/beacons.md
  wiki/faq.md
  wiki/scraper.md
  wiki/staking.md
Labels: enhancement, rewording
